server:
  port: 8682
  servlet:
    context-path: /dex

#数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dex?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: 7760608
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
  redis:
    host: 172.20.17.41
    port: 6379
  application:
    name: dex-busman
  cloud:
    nacos:
      discovery:
        server-addr: 172.20.17.42:8848
    sentinel:
      transport:
        dashboard: 172.20.17.42:8086

#mybatis
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml



