server:
  port: 8683
  servlet:
    context-path: /dex

#数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dex?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: 7760608
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
  redis:
    host: 172.20.17.41
    port: 6379
  application:
    name: dex-admin
  cloud:
    nacos:
      discovery:
        server-addr: 172.20.17.42:8848

    sentinel:
      transport:
        #配置sentinel dashhost的地址
        dashboard: 172.20.17.42:8086
        #默认8719端口，加入被占用会自动从8719开始依次+1扫描，直至找到未被占用的端口
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr: 172.20.17.42:8848
            dataid: dex-admin
            groupid: DEFAULT_GROUP
            data-type: json
            rule-type: flow


management:
  endpoints:
    web:
      exposure:
        include: '*'


#mybatis
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml







